apiVersion: apps/v1
kind: Deployment
metadata:
  name: whale
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: whale
  template:
    metadata:
      labels:
        app: whale
    spec:
      containers:
      - image: howard666/dummy
        name: whale
        ports:
        - containerPort: 80
